name: Packer Workflow

on:
  push:
    branches:
      - '**'  

jobs:
  validate:
    name: Validate Packer Template
    runs-on: ubuntu-latest
    env:
      PRODUCT_VERSION: "1.11.0"
      TEMPLATE_PATH: "../../template/ubuntu-golden-image.pkr.hcl"

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Packer
      uses: hashicorp/setup-packer@v3
      with:
        version: "${{env.PRODUCT_VERSION}}"

    - name: Run `packer init`
        id: init
        run: packer init "${{env.TEMPLATE_PATH}}"

    - name: Validate Packer template
      run: packer validate "${{env.TEMPLATE_PATH}}"

  build:
    name: Build Packer Template
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    needs: validate 
    environment:
      name: production
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Packer
      uses: hashicorp/setup-packer@v3
      with:
        version: "${{env.PRODUCT_VERSION}}"

    - name: Run `packer init`
        id: init
        run: packer init "${{env.TEMPLATE_PATH}}"

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.REGION }}

    - name: Build Packer template
      run: packer build "${{env.TEMPLATE_PATH}}"
